apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cw-coinbase-deployment
  labels:
    app: cloud-cw-coinbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-cw-coinbase
  template:
    metadata:
      labels:
        app: cloud-cw-coinbase 
    spec:
      containers:
      - name: nodeserver
        image: manupriyalogus/cloud-cw-coinbase-0.0.1:latest
        ports:
        - containerPort: 8080