
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-deployment
  labels:
    app: coinbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbase
  template:
    metadata:
      labels:
        app: coinbase 
    spec:
      containers:
      - name: nodeserver
        image: manupriyalogus/cloud-cw-coinbase:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: coinbase-service
spec:
  selector:
    app: coinbase 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
