apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cw-coinbase-deployment-test
  labels:
    app: cloud-cw-coinbase-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-cw-coinbase-test
    version: blue
  template:
    metadata:
      labels:
        app: cloud-cw-coinbase-test
    spec:
      containers:
      - name: nodeserver
        image: manupriyalogus/cloud-cw-coinbase:latest
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-cw-coinbase-service-test
spec:
  selector:
    app: cloud-cw-coinbase-test
    version: blue
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 31110