apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cw-coinbase-blue
  labels:
    app: cloud-cw-coinbase
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-cw-coinbase
      version: blue
  template:
    metadata:
      labels:
        app: cloud-cw-coinbase
        version: blue
    spec:
      containers:
      - name: appserver
        image: manupriyalogus/cloud-cw-coinbase:1.1.0
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-cw-coinbase-service-stable
spec:
  selector:
    app: cloud-cw-coinbase
    version: blue
#    version : green
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080